#!/usr/bin/env python3
"""Build the Big Bear Planetariums sub-pages and keep the shared header,
mobile menu and footer identical on every page.

Run from the repo root:  python3 tools/build.py

- Writes schools.html, corporate-groups.html, private-parties.html and
  festivals-events.html from the PAGES data below.
- Rewrites the blocks between <!-- @top --> / <!-- /@top --> and
  <!-- @bottom --> / <!-- /@bottom --> in index.html.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PHONE, PHONE_TEL = "083 800 1933", "0838001933"
EMAIL = "info@bigbearplanetariums.ie"
FACEBOOK = "https://www.facebook.com/bigbearplanetariums/"

# Order here is the order in the nav, menu and footer.
NAV_PAGES = [
    ("schools.html", "Primary &amp; Secondary Schools", "Schools", "🚀", "Curriculum-linked shows for every class"),
    ("corporate-groups.html", "Corporate Groups", "Corporate", "💼", "Team days, family days and events"),
    ("private-parties.html", "Private Parties", "Parties", "🎂", "Birthdays under the stars"),
    ("festivals-events.html", "Festivals &amp; Events", "Festivals", "🎪", "The attraction everyone queues for"),
]

ARROW = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg>'
CHEV = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M6 9l6 6 6-6"/></svg>'
PLAY = '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>'
CLOSE = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg>'


def top(current):
    """Background layers, header with dropdown, and the mobile menu."""
    home = "" if current == "index.html" else "index.html"
    brand_href = "#top" if current == "index.html" else "index.html"
    cur = lambda f: ' aria-current="page"' if f == current else ""
    dd = "\n".join(
        f'          <a href="{f}"{cur(f)}><i>{em}</i><span>{full}<small>{blurb}</small></span></a>'
        for f, full, _, em, blurb in NAV_PAGES)
    mpages = "\n".join(
        f'  <a class="m-page" href="{f}"{cur(f)}><i>{em}</i>{full}</a>' for f, full, _, em, _ in NAV_PAGES)
    home_link = '' if current == "index.html" else '<a href="index.html">Home</a>'
    return f'''<!-- @top -->
<div class="nebula" aria-hidden="true"><i></i><i></i><i></i></div>
<canvas id="stars"></canvas>
<div class="cursor" id="cursor"></div>
<div class="progress" id="progress"></div>

<!-- ================= NAV (generated by tools/build.py) ================= -->
<header id="header">
  <div class="wrap nav">
    <a href="{brand_href}" class="brand" aria-label="Big Bear Planetariums home">
      <img src="img/logo-sm.png" alt="Big Bear Planetariums logo" width="44" height="48">
      <span>Big Bear<small>PLANETARIUMS</small></span>
    </a>
    <nav class="links" id="links">
      <a href="{home}#about">About</a>
      <div class="dd">
        <button type="button" aria-haspopup="true">Shows for {CHEV}</button>
        <div class="dd-menu">
{dd}
        </div>
      </div>
      <a href="{home}#videos">Videos</a>
      <a href="{home}#gallery">Gallery</a>
      <a href="#book" class="btn btn-primary btn-sm">Book a show</a>
    </nav>
    <button class="burger" id="burger" aria-label="Open menu" aria-expanded="false"><span></span><span></span></button>
  </div>
</header>
<nav class="mnav" id="mnav" aria-label="Mobile menu">
  <span class="m-label">Shows for</span>
{mpages}
  <div class="m-small">{home_link}<a href="{home}#about">About</a><a href="{home}#videos">Videos</a><a href="{home}#gallery">Gallery</a><a href="#faq">FAQ</a></div>
  <a class="m-call" href="tel:{PHONE_TEL}">Call {PHONE}</a>
  <a href="#book" class="btn btn-primary">Book a show</a>
</nav>
<!-- /@top -->'''


def bottom(current):
    home = "" if current == "index.html" else "index.html"
    pages = "".join(f'<a href="{f}">{short}</a>' for f, _, short, _, _ in NAV_PAGES)
    return f'''<!-- @bottom -->
<footer>
  <div class="wrap">
    <div class="foot">
      <a href="{home or '#top'}" class="brand"><img src="img/logo-sm.png" alt="" width="56" height="61"><span>Big Bear<small>PLANETARIUMS</small></span></a>
      <nav>{pages}<a href="{home}#videos">Videos</a><a href="{home}#gallery">Gallery</a><a href="#book">Book</a><a href="tel:{PHONE_TEL}">{PHONE}</a><a href="mailto:{EMAIL}">Email</a><a href="{FACEBOOK}" target="_blank" rel="noopener">Facebook</a></nav>
    </div>
    <div class="copy"><span>© <span id="yr"></span> Big Bear Planetariums · Ireland</span><span>Educate and Inspire ✦</span></div>
  </div>
</footer>

<div class="lightbox" id="lightbox" role="dialog" aria-modal="true" aria-label="Photo viewer">
  <img id="lbImg" alt="">
  <div class="cap" id="lbCap"></div>
  <button class="lb-btn lb-close" id="lbClose" aria-label="Close">{CLOSE}</button>
  <button class="lb-btn lb-prev" id="lbPrev" aria-label="Previous"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 6l-6 6 6 6"/></svg></button>
  <button class="lb-btn lb-next" id="lbNext" aria-label="Next"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 6l6 6-6 6"/></svg></button>
</div>

<div class="lightbox" id="vidbox" role="dialog" aria-modal="true" aria-label="Video player">
  <video id="promo" controls playsinline preload="none" style="width:min(92vw,1100px);max-height:84vh;border-radius:16px;background:#000;box-shadow:0 40px 100px rgba(0,0,0,.7)"></video>
  <button class="lb-btn lb-close" id="vidClose" aria-label="Close video">{CLOSE}</button>
</div>

<button class="to-top" id="toTop" aria-label="Back to top"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 19V5M6 11l6-6 6 6"/></svg></button>
<!-- /@bottom -->'''


def vid_card(src, poster, title, length, preview=None, cls=""):
    pv = f'<video muted loop playsinline preload="none" data-src="{preview}"></video>' if preview else ""
    return f'''      <button class="vid-card rv {cls}" data-src="{src}" data-poster="{poster}">
        <img src="{poster}" alt="" loading="lazy">{pv}
        <span class="vid-play">{PLAY}</span>
        <span class="vid-meta"><b>{title}</b><small>{length}</small></span>
      </button>'''


def faq_html(items):
    return "\n".join(f'      <details><summary>{q}<i></i></summary><div class="ans"><p>{a}</p></div></details>' for q, a in items)


STEM = [
    ("S", "Science", "Physics, chemistry, biology &amp; earth science", "#6fc3ff",
     ["How stars are born, shine and die", "The Sun, Moon, planets and the seasons", "Gravity, light and the colours of the sky", "Life on Earth and the search for life beyond it"]),
    ("T", "Technology", "The tools that let us explore", "#9b6bff",
     ["Telescopes, satellites and space probes", "How we photograph galaxies billions of light-years away", "Data, sensors and the technology behind every mission", "The digital dome and how it is projected"]),
    ("E", "Engineering", "Designing things that work in space", "#e46fb4",
     ["Rockets, launchers and how they reach orbit", "Space stations and the Moon landings", "Rovers and robots exploring Mars", "How astronauts live, work and stay safe"]),
    ("M", "Maths", "Numbers, patterns and shapes in the sky", "#ffc861",
     ["Scale: how big is the Universe, really?", "Distances, light-years and travel times", "Orbits, circles, ellipses and geometry", "Patterns, cycles and counting the stars"]),
]


def stem_section(sec_id=None, tight=False):
    idattr = f' id="{sec_id}"' if sec_id else ""
    pad = "padding-top:0;padding-bottom:clamp(40px,6vw,70px)" if tight else "padding-top:0"
    cards = "\n".join(
        f'''      <div class="stem rv" style="--c:{c};transition-delay:{i * .08:.2f}s">
        <span class="letter">{l}</span>
        <h3>{name}</h3><span class="sub">{sub}</span>
        <ul>{"".join(f"<li>{b}</li>" for b in bullets)}</ul>
      </div>''' for i, (l, name, sub, c, bullets) in enumerate(STEM))
    return f'''<!-- @stem -->
<section{idattr} class="stem-wrap" style="{pad}">
  <div class="wrap">
    <div class="head">
      <div>
        <span class="eyebrow rv">Our shows</span>
        <h2 class="rv">All <span class="grad-text">STEM</span> subjects covered</h2>
      </div>
      <p class="lead rv" style="max-width:46ch">Space is the doorway to every STEM subject. Our live, interactive shows weave science, technology, engineering and maths together, pitched to the age of the group in front of us.</p>
    </div>
    <div class="stem-grid">
{cards}
    </div>
  </div>
</section>
<!-- /@stem -->'''


# ---------------------------------------------------------------------------
# Page content
# ---------------------------------------------------------------------------
PAGES = [
    dict(
        file="schools.html", type="Primary school",
        title="Primary &amp; Secondary Schools | Big Bear Planetariums",
        desc="A mobile planetarium for primary and secondary schools in Ireland. Live, curriculum-linked shows inside our inflatable planetarium, in your own school hall.",
        bg="rocket-bg", eyebrow="For schools",
        h1='We bring the <span class="grad-text">universe</span> to you.',
        lead="A full planetarium, right in your school hall. Classes take turns stepping inside the dome for a live, interactive show under the stars, and nobody has to leave the building.",
        intro_h='A school trip <span class="grad-text">without the bus</span>',
        intro_p="No coaches, no permission slips and no lost teaching time. We arrive, inflate the dome in your hall or gym, and classes come to us one after another. Every show is presented live, so we pitch it to each group and answer their questions as we go.",
        intro_img="school-group-2", intro_alt="A class cheering in front of the planetarium dome",
        feats=[("🏫", "No trip needed", "The planetarium comes to you, so the whole day happens on your own school grounds."),
               ("🗓️", "Whole-school days", "We plan a timetable with you so class after class gets their turn in the dome."),
               ("🧒", "Every age", "From junior infants to Leaving Cert, each show is pitched to the class in front of us."),
               ("☔", "Any weather", "Indoors in your hall or gym, the sky inside the dome is always clear.")],
        duo=[("primary", "Primary Schools", "From junior infants to sixth class",
              "Big wonder for small astronomers. Children lie back, look up and explore the night sky together.",
              ["<b>Science:</b> the Sun, Moon, planets, day and night, and the seasons", "<b>Technology:</b> telescopes, satellites and how we look at space",
               "<b>Engineering:</b> rockets, astronauts and the Moon landings", "<b>Maths:</b> shapes, sizes, patterns and counting the stars",
               "Links with primary science and SESE geography"]),
             ("secondary", "Secondary Schools", "Junior Cycle, TY and Leaving Cert",
              "Deeper journeys for curious minds, from how stars are born to the edge of the observable universe.",
              ["<b>Science:</b> the life cycle of stars, from nebulae to black holes", "<b>Technology:</b> how telescopes, probes and data reveal the universe",
               "<b>Engineering:</b> spacecraft, space stations and missions happening now", "<b>Maths:</b> the scale of the universe, light-years, orbits and gravity",
               "Supports the Junior Cycle Science Earth and Space strand, and a great fit for Transition Year and Science Week"])],
        videos=[("video/rocket.mp4", "video/rocket.jpg", "Rocket adventure", "0:46", "video/rocket-bg.mp4", "big"),
                ("video/inside-the-dome.mp4", "video/inside-the-dome.jpg", "Inside the dome", "0:17", "video/inside-the-dome-preview.mp4", "")],
        gallery="schools", gallery_h='Schools we&rsquo;ve <span class="grad-text">visited</span>',
        faq=[("How much space do you need?", "A school hall, sports hall or large room with enough floor space and headroom for the dome. Tell us about your hall and we'll confirm it's a fit before the day."),
             ("How many classes can see a show?", "We plan a timetable with you so groups rotate through the dome across the day. Let us know how many classes you have and we'll work it out together."),
             ("What do we need to provide?", "Just the space and access to a standard power socket. We bring the dome, the projection equipment and everything else."),
             ("Can every child take part?", "Talk to us about any access or sensory needs in your group and we'll plan the show around them.")],
    ),
    dict(
        file="corporate-groups.html", type="Corporate group",
        title="Corporate Groups | Big Bear Planetariums",
        desc="Mobile planetarium experiences for corporate team events, family days, conferences and exhibitions across Ireland.",
        bg="station-bg", eyebrow="For companies",
        h1='Take your team <span class="grad-text">out of this world</span>',
        lead="A mobile planetarium turns any event into something people talk about for weeks. Step inside our dome for a live journey through space, right in your office, venue or event space.",
        intro_h='An event people <span class="grad-text">remember</span>',
        intro_p="Most team events are forgotten by Monday. Lying back under a sky full of stars isn't. We set up the dome at your venue, run live shows back to back, and take care of everything so your team just enjoys it.",
        intro_img="dome-black-hall", intro_alt="Both Big Bear domes set up side by side in a hall",
        feats=[("🤝", "Team events", "A shared experience that gets people talking, perfect for away days and team building."),
               ("👨‍👩‍👧", "Family &amp; fun days", "A stand-out attraction for staff family days that kids and adults both love."),
               ("🎤", "Conferences &amp; exhibitions", "Draw a crowd to your stand or event with a dome people queue to get into."),
               ("🌍", "Community days", "Bring the planetarium to a local school or community group as part of your company's community work.")],
        duo=None,
        videos=[("video/space-station.mp4", "video/station-bg.jpg", "Journey to the space station", "1:11", "video/station-bg.mp4", "big"),
                ("video/festival-day.mp4", "video/festival-day.jpg", "A dome at an event", "0:28", "video/festival-day-preview.mp4", "")],
        gallery="setup,outdoor", gallery_h='The domes <span class="grad-text">on location</span>',
        faq=[("Where can you set up?", "In any hall, atrium, marquee or large room with enough floor space and headroom, or outdoors on a level grassy area. Tell us about your venue and we'll confirm it's a fit."),
             ("Can the show be tailored to our event?", "Yes. Every show is presented live, so we can shape it around your audience and your day. Talk to us about what you have in mind."),
             ("What do you need from us?", "The space and access to a standard power socket. We bring the dome, projection equipment and everything else, and pack it all away afterwards."),
             ("How do we get a quote?", f"Call us on {PHONE} or send the form below with your date, venue and rough numbers and we'll come back to you.")],
    ),
    dict(
        file="private-parties.html", type="Private party",
        title="Private Parties | Big Bear Planetariums",
        desc="Birthday parties and private celebrations with a mobile planetarium. We bring the dome and the stars to your party anywhere in Ireland.",
        bg="party-bg", eyebrow="For parties",
        h1='A party <span class="grad-text">among the stars</span>',
        lead="Forget the bouncy castle. Give your guests a birthday they'll never forget, with a real planetarium dome and a live journey through space.",
        intro_h='The birthday <span class="grad-text">everyone talks about</span>',
        intro_p="We arrive, inflate the dome and take your guests on a live tour of the night sky, pitched just right for the birthday child and their friends. You enjoy the party while we look after the show.",
        intro_img="school-group-4", intro_alt="Young children excited in front of the planetarium dome",
        feats=[("🎈", "Birthday parties", "Space-mad kids, curious teens or grown-ups who never stopped looking up."),
               ("🌌", "Tailored shows", "Tell us what the birthday star loves most: planets, rockets or black holes."),
               ("🏠", "At your venue", "A community hall, function room or large indoor space, or a garden in good weather."),
               ("✨", "Stress-free", "We bring everything, run the shows and pack it all away afterwards.")],
        duo=None,
        phone=("video/promo-4k.mp4", "video/promo-4k.jpg"),
        videos=[("video/inside-the-dome.mp4", "video/inside-the-dome.jpg", "Inside the dome", "0:17", "video/inside-the-dome-preview.mp4", "big"),
                ("video/rocket.mp4", "video/rocket.jpg", "Rocket adventure", "0:46", "video/rocket-bg.mp4", "")],
        gallery="setup,community", gallery_h='A look <span class="grad-text">behind the scenes</span>',
        faq=[("How much space do we need?", "Enough floor space and headroom for the dome, like a community hall, function room or large indoor space. Tell us about your venue and we'll confirm it's a fit."),
             ("What ages is it for?", "All of them. We pitch every show to the group in front of us, from little ones to adults."),
             ("Can you come to our house?", "If you have a large enough room, or a level garden in good weather, possibly. Send us the details and we'll let you know."),
             ("How do I book?", f"Call us on {PHONE} or send the form below with the date, venue and number of guests.")],
    ),
    dict(
        file="festivals-events.html", type="Festival / event",
        title="Festivals &amp; Events | Big Bear Planetariums",
        desc="A mobile planetarium for festivals, fun days, fairs and community events in Ireland. Indoor or outdoor, with shows running all day.",
        bg="festival-bg", eyebrow="For festivals &amp; events",
        h1='The attraction <span class="grad-text">everyone queues for</span>',
        lead="From summer festivals to Science Week, our domes draw the crowds. Shows run back to back all day, indoors or out, and every visitor leaves with stars in their eyes.",
        intro_h='Big crowds, <span class="grad-text">big wonder</span>',
        intro_p="Our domes have become a favourite at festivals and fun days. Look for the big blue sky dancers! We run short live shows back to back, so the queue keeps moving and everyone gets their turn under the stars.",
        intro_img="festival-queue", intro_alt="Families queueing for a planetarium show at a festival",
        feats=[("🌤️", "Indoor or outdoor", "On a level field at your festival, or inside a hall or marquee."),
               ("🕺", "Impossible to miss", "Two giant sky dancers and our banners let people know where the stars are."),
               ("🔁", "Shows all day", "Short live shows run back to back to keep the crowds moving."),
               ("👨‍👩‍👧‍👦", "For every age", "Toddlers, teens, parents and grandparents, all under the same sky.")],
        duo=None,
        videos=[("video/festival-park.mp4", "video/festival-park.jpg", "A day in the park", "0:56", "video/festival-park-preview.mp4", "big"),
                ("video/festival-day.mp4", "video/festival-day.jpg", "Festival day", "0:28", "video/festival-day-preview.mp4", "")],
        gallery="outdoor", gallery_h='Festivals <span class="grad-text">we&rsquo;ve lit up</span>',
        faq=[("Can the dome go outdoors?", "Yes. We need a level grassy area, and we bring ground sheets and barriers. We'll talk through the site with you before the day."),
             ("How many people can see a show?", "We run short shows back to back all day so the queue keeps moving. Tell us your expected numbers and we'll plan around them."),
             ("What do you need on site?", "Access to power and the space for the dome and a small queue area. We bring everything else."),
             ("How do we book?", f"Call us on {PHONE} or send the form below with your event dates and location.")],
    ),
]


def head(title, desc):
    return f'''<!DOCTYPE html>
<html lang="en-IE">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#07061a">
<link rel="icon" type="image/png" href="img/favicon.png">
<meta property="og:type" content="website">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:image" content="og-image.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700&family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="css/site.css">
</head>'''


def page(p):
    f = p["file"]
    feats = "\n".join(
        f'      <div class="feat rv" style="transition-delay:{i * .08:.2f}s"><span class="em">{em}</span><h3>{h}</h3><p>{t}</p></div>'
        for i, (em, h, t) in enumerate(p["feats"]))
    duo = ""
    if p.get("duo"):
        cols = "\n".join(f'''      <div id="{i}" class="rv">
        <span class="eyebrow">{sub}</span>
        <h3>{h}</h3>
        <p class="lead">{t}</p>
        <ul>{"".join(f"<li>{b}</li>" for b in bullets)}</ul>
      </div>''' for i, h, sub, t, bullets in p["duo"])
        duo = f'''
<section style="padding-top:0">
  <div class="wrap">
    <div class="duo">
{cols}
    </div>
  </div>
</section>
'''
    phone = ""
    if p.get("phone"):
        src, poster = p["phone"]
        phone = f'''
<section style="padding-top:0">
  <div class="wrap split">
    <div>
      <span class="eyebrow rv">Only with Big Bear</span>
      <h2 class="rv">Experience it in <span class="grad-text">true 4K</span></h2>
      <p class="lead rv">Crystal-clear stars, planets you could almost touch and a sky that wraps all the way around you. Tap the video to see what your guests are in for.</p>
      <a href="#book" class="btn btn-primary magnetic rv" style="margin-top:28px">Book your party {ARROW}</a>
    </div>
    <div class="phone-vid rv s" data-play="{src}" data-poster="{poster}" role="button" tabindex="0" aria-label="Play video">
      <img src="{poster}" alt="" loading="lazy"><span class="vid-play">{PLAY}</span>
    </div>
  </div>
</section>
'''
    vids = "\n".join(vid_card(*v) for v in p["videos"])
    others = "\n".join(
        f'      <a class="xl rv" href="{of}"><img src="img/{img}-sm.webp" alt="" loading="lazy"><span><b>{full}</b><small>{blurb}</small></span></a>'
        for (of, full, _, _, blurb), img in zip(NAV_PAGES, ["school-group-2", "dome-black-hall", "school-group-4", "festival-queue"])
        if of != f)
    bgsrc = p["bg"]
    return f'''{head(p["title"], p["desc"])}
<body class="loading">

{top(f)}

<main id="top">
<!-- ================= HERO ================= -->
<section class="hero page-hero">
  <div class="hero-video" id="heroMedia">
    <video id="heroVid" muted loop playsinline autoplay preload="auto" poster="video/{bgsrc}.jpg">
      <source src="video/{bgsrc}.mp4" type="video/mp4"><source src="video/{bgsrc}.webm" type="video/webm">
    </video>
  </div>
  <div class="wrap">
    <div class="crumbs hero-fade"><a href="index.html">Home</a><span>›</span><span>{p["eyebrow"].replace("For ", "").capitalize()}</span></div>
    <span class="eyebrow hero-fade">{p["eyebrow"]}</span>
    <h1 class="hero-fade d1" style="margin-top:16px">{p["h1"]}</h1>
    <p class="hero-fade d2">{p["lead"]}</p>
    <div class="cta hero-fade d3">
      <a href="#book" class="btn btn-primary magnetic">Book a show {ARROW}</a>
      <a href="tel:{PHONE_TEL}" class="btn btn-ghost magnetic">Call {PHONE}</a>
    </div>
  </div>
  <a href="#intro-sec" class="scroll-cue" aria-label="Scroll down"><b></b>Scroll</a>
</section>

<!-- ================= INTRO ================= -->
<section id="intro-sec">
  <div class="wrap split">
    <div>
      <span class="eyebrow rv">Why Big Bear</span>
      <h2 class="rv">{p["intro_h"]}</h2>
      <p class="lead rv">{p["intro_p"]}</p>
      <a href="#book" class="btn btn-primary magnetic rv" style="margin-top:28px">Check availability {ARROW}</a>
    </div>
    <div class="split-img rv r"><img src="img/{p["intro_img"]}.webp" alt="{p["intro_alt"]}" loading="lazy"></div>
  </div>
</section>

<section style="padding-top:0">
  <div class="wrap">
    <div class="feats">
{feats}
    </div>
  </div>
</section>
{stem_section(tight=bool(p.get("duo")))}
{duo}{phone}
<!-- ================= VIDEOS ================= -->
<section id="videos" style="padding-top:0">
  <div class="wrap">
    <div class="head">
      <div>
        <span class="eyebrow rv">Watch</span>
        <h2 class="rv">See it <span class="grad-text">in action</span></h2>
      </div>
      <p class="lead rv" style="max-width:40ch">Tap a video to watch it with sound.</p>
    </div>
    <div class="vids two">
{vids}
    </div>
  </div>
</section>

<!-- ================= GALLERY ================= -->
<section id="gallery" style="padding-top:0">
  <div class="wrap">
    <div class="head"><div><span class="eyebrow rv">Gallery</span><h2 class="rv">{p["gallery_h"]}</h2></div></div>
    <div class="gallery" id="gallery-grid" data-cats="{p["gallery"]}" data-limit="9"></div>
    <div class="more-wrap"><button class="btn btn-ghost" id="moreBtn">Show all photos</button></div>
  </div>
</section>

<!-- ================= FAQ ================= -->
<section id="faq" style="padding-top:0">
  <div class="wrap faq-wrap">
    <div>
      <span class="eyebrow rv">FAQ</span>
      <h2 class="rv">Good <span class="grad-text">questions</span></h2>
      <p class="lead rv">Anything else? Call us on <a href="tel:{PHONE_TEL}" style="color:var(--sky)">{PHONE}</a>. We're always happy to talk space.</p>
    </div>
    <div class="faq rv">
{faq_html(p["faq"])}
    </div>
  </div>
</section>

<!-- ================= BOOK ================= -->
<section id="book" style="padding-top:0">
  <div class="wrap contact">
    <div class="contact-card rv l">
      <span class="eyebrow">Book a show</span>
      <h2>Ready for <span class="grad-text">lift-off?</span></h2>
      <p class="lead">Tell us your date, venue and group and we'll get back to you with availability and a quote.</p>
      <div class="contact-info" id="contactInfo"></div>
    </div>
    {FORM.format(type=p["type"])}
  </div>
</section>

<!-- ================= MORE ================= -->
<section style="padding-top:0">
  <div class="wrap">
    <div class="head"><div><span class="eyebrow rv">Explore</span><h2 class="rv">Who else we <span class="grad-text">visit</span></h2></div></div>
    <div class="crosslinks">
{others}
    </div>
  </div>
</section>
</main>

{bottom(f)}

<script src="js/site.js"></script>
</body>
</html>
'''


FORM = '''<form id="bookForm" class="rv r" novalidate data-type="{type}">
      <div class="field"><label for="f-name">Your name</label><input id="f-name" name="name" required autocomplete="name"></div>
      <div class="field"><label for="f-email">Email</label><input id="f-email" name="email" type="email" required autocomplete="email"></div>
      <div class="field"><label for="f-phone">Phone</label><input id="f-phone" name="phone" type="tel" autocomplete="tel"></div>
      <div class="field"><label for="f-type">Booking for</label>
        <select id="f-type" name="type"><option>Primary school</option><option>Secondary school</option><option>Corporate group</option><option>Private party</option><option>Festival / event</option><option>Library / community</option><option>Other</option></select></div>
      <div class="field"><label for="f-date">Preferred date</label><input id="f-date" name="date" type="date"></div>
      <div class="field"><label for="f-county">County</label><select id="f-county" name="county"></select></div>
      <div class="field full"><label for="f-msg">Tell us more</label><textarea id="f-msg" name="message" placeholder="Venue, group size, ages, anything else…"></textarea></div>
      <div class="field full"><button type="submit" class="btn btn-primary magnetic" style="justify-content:center">Send enquiry <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14M13 6l6 6-6 6"/></svg></button></div>
      <p class="form-note">Sending opens your email app with your details filled in.</p>
      <div class="form-ok" id="formOk">Thanks! Your email app should now be open. Just press send and we'll be in touch soon. ✨</div>
    </form>'''


def main():
    for p in PAGES:
        with open(os.path.join(ROOT, p["file"]), "w") as fh:
            fh.write(page(p))
        print("wrote", p["file"])
    ip = os.path.join(ROOT, "index.html")
    s = open(ip).read()
    s = re.sub(r"<!-- @top -->.*?<!-- /@top -->", lambda m: top("index.html"), s, flags=re.S)
    s = re.sub(r"<!-- @stem -->.*?<!-- /@stem -->", lambda m: stem_section("shows"), s, flags=re.S)
    s = re.sub(r"<!-- @bottom -->.*?<!-- /@bottom -->", lambda m: bottom("index.html"), s, flags=re.S)
    open(ip, "w").write(s)
    print("updated index.html header/footer")


if __name__ == "__main__":
    main()
